services:
  api:
    depends_on:
      - postgres
    build:
      context: .
    ports:
      - 80:3000
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres

  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./misc/database:/docker-entrypoint-initdb.d
    env_file:
      - .env
